# Generated by Django 5.1.5 on 2025-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_choice', models.CharField(choices=[('full', 'Full Meal'), ('guest', 'Guest Meal'), ('half_day', 'Lunch & Breakfast'), ('half_night', 'Dinner & Breakfast')], default='full', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
