# Generated by Django 5.1.5 on 2025-01-23 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('full_price', models.FloatField()),
                ('half_price', models.FloatField()),
                ('is_half_meal_combination', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_choice', models.CharField(choices=[('full', 'Full Meal'), ('guest', 'Guest Meal'), ('half_day', 'Lunch & Breakfast'), ('half_night', 'Dinner & Breakfast')], default='full', max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_model')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealtype')),
            ],
        ),
    ]
