# Generated by Django 5.1.5 on 2025-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='description',
            field=models.TextField(default='For me'),
        ),
    ]
