# Generated by Django 5.1.5 on 2025-02-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='is_paid',
        ),
    ]
