# Generated by Django 5.1.5 on 2025-01-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_user'),
        ('user', '0003_alter_user_model_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='user.user_model'),
        ),
    ]
