# Generated by Django 5.1.5 on 2025-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_alter_user_model_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='student_permissions', to='auth.permission'),
        ),
    ]
