# Generated by Django 5.1.5 on 2025-02-15 02:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_complaint_admin_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('mess_rent', 'Mess Rent'), ('water', 'Water Bill'), ('khala', 'Khala Bill'), ('net', 'Net Bill'), ('current', 'Current Bill'), ('other', 'Other')], default='all', max_length=20),
        ),
    ]
