# Generated by Django 5.1.5 on 2025-02-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('all_fixed', 'All Fixed Bills'), ('mess_rent', 'Mess Rent'), ('water', 'Water'), ('khala', 'Khala'), ('net', 'Internet'), ('current', 'Electricity'), ('other', 'Other')], default='all_fixed', max_length=20),
        ),
    ]
