# Generated by Django 5.1.5 on 2025-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='seat_rent',
            field=models.DecimalField(decimal_places=2, default=950.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user_model',
            name='seat_type',
            field=models.CharField(choices=[('double_bed', 'Double Bed Room'), ('private', 'Private Room')], default='double_bed', max_length=20),
        ),
    ]
