# Generated by Django 5.1.5 on 2025-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bill_payment_date_bill_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
